### ISSUE TITLE
unable to prevent some classes from being scoped.

### ISSUE THREAD

**Issue by TheMcMurder** [CanopyTax/kremling-loader#10]
example:

````html
<div class='myGlobalClass'>
  <MyComponent />
</div>
````

````jsx
import css from './css'
function MyComponent() {
  const scope = useCss(css)
 return (
   <div {...scope} className='myScopedClass'>
    Hello   
   </div>
 )
}
````

````css
.myGlobalClass .myScopedClass {
  color: red;
}
````

I'd like a way to signal to the kremling loader that `myGlobalClass` shouldn't be scoped. An example of this using CSS modules looks like this.

````css
:global(.myGlobalClass) .myScopedClass {
  color: red;
}
````

As far as I can tell currently the kremling loader doesn't support _not_ scoping a portion of the css selector.
