### ISSUE TITLE
kremling-loader and runtime css string do not work together

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/kremling-loader#4]
If you're using both raw css and postcss, both have a counter that starts at zero and increment from there. This makes the css rules generated conflict with each other.

```css
/* generated with kremling-loader */
[kremling="0"] .hello, [kremling="0"].hello {
  color: navajowhite;
}

/* generated with raw css in browser */
[kremling="0"] .hello, [kremling="0"].hello {
  color: lawngreen;
}
```

^^ This is a problem because they have the same "0" which makes their css scopes overlap. Suggested solution would be to append a prefix or something in front of kremling-loader's attribute values. Maybe `[kremling="p0"] .hello`? `P` for `postcss`?? idk
